codejockie/document-manager

.eslintrc.json, .gitignore, package.json
initialise package.json, add eslintrc.json and gitignore
Finishes #148130447
=> chore(flight): setup project

README.md
=> chore(flight): add project readme

.eslintrc.json, .hound.yml
#148968221 Fix Hound ES6 warnings
=> bug(flight): fix hound warnings

server/migrations/20170707092042-create-user.js, server/migrations/20170707092043-create-document.js, server/models/document.js, server/models/user.js, server/seeders/20170716114450-roles_seeder.js, server/seeders/20170719104129-users_seeder.js
#149215871 Fix Migrations/Models
=> bug(flight): fix migrations/models

package.json, tests/routes/documents.spec.js
#148729309 Write Tests for Documents Endpoints
=> chore(finish): tests for documents endpoints

tests/routes/users.spec.js
#149340753 Write Tests for Users Endpoints
=> chore(finish): tests for users endpoints

.travis.yml, gulpfile.babel.js, package.json, server/config/config.json, server/models/index.js
#149340957 Integrate a Continuous Integration Tool
=> chore(finish): integrate Travis CI

.codeclimate.yml, README.md, package.json
#149340967 Add CI Tools badges
=> chore(finish): add CI tools badges

.codeclimate.yml, .travis.yml, README.md, package.json, tests/routes/documents.spec.js, tests/routes/search.spec.js, tests/routes/users.spec.js
=> chore(finish): fix README

.codeclimate.yml, .travis.yml, README.md, gulpfile.babel.js, package.json, tests/routes/documents.spec.js, tests/routes/search.spec.js, tests/routes/users.spec.js
=> chore(finish): abstract tokens

server/config/config.json, server/helpers/middleware.js, server/models/index.js, server/routes/documents.js, server/routes/search.js, server/routes/users.js, tests/routes/documents.spec.js, tests/routes/users.spec.js
#149780495 exceed test expectation
=> chore(finish): exceed test expectation

package.json
#149780625 write api documentation
=> bug(finish): fix heroku app crash

.gitignore, gulpfile.babel.js, package.json, public/index.html, server/models/index.js, server/routes/documents.js, server/routes/search.js, server/routes/users.js, tests/routes/documents.spec.js, tests/routes/search.spec.js, tests/routes/users.spec.js
#149794556 unify documentation
=> chore(flight): unify documentation

.gitignore, .travis.yml, gulpfile.babel.js, package.json, server/config/config.json, server/server.js
#149982169 switch to travis postgresql
=> chore(flight): switch to travis postgresql

server/controllers/documentController.js, server/controllers/roleController.js, server/controllers/searchController.js, server/controllers/userController.js, server/helpers/helper.js, tests/controllers/users.spec.js
This PR implements feedback received
N/A
N/A
No
Feedback Implementation 4
N/A
None
=> #150239544 feedback implementation 4

.babelrc, .gitignore, .nycrc, __tests__/server/controllers/documents.spec.js, __tests__/server/controllers/roles.spec.js, __tests__/server/controllers/search.spec.js, __tests__/server/controllers/users.spec.js, client/assets/template.html, client/index.js, package.json, server/server.js, webpack.config.babel.js, yarn.lock
This PR adds basic client side setup to the project. It heralds the beginning of the client implementation with React.
=> Chore 154837053 configure client app

client/src/actions/index.js, client/src/components/App.js, client/src/components/Main.js, client/src/containers/Header.js, client/src/containers/auth/SignOut.js, client/src/infrastructure/styles.js
In this PR I added the header to the app.
=> (feat): implement app header

client/src/actions/index.js, client/src/components/Main.js, client/src/containers/Header.js, client/src/containers/auth/SignUp.js, client/src/infrastructure/styles.js, client/src/reducers/authReducer.js
In this PR I added the sign up page and implemented it functionalities. I also created the signup action creator.
=> Feat: Add sign up page and implement sign up action

.codeclimate.yml, client/src/components/hoc/RequireAuth.js, client/src/index.js
In this PR I added a higher order component for requiring authentication. When it wraps a component it ensures the user is authenticated before been given access to that component.
I also included automatic authentication which allows the authentication state to be persisted when the page is refreshed.
=> Feat: Implement auto authentication

.travis.yml, __tests__/server/controllers/auth.spec.js, __tests__/server/controllers/documents.spec.js, __tests__/server/controllers/roles.spec.js, __tests__/server/controllers/search.spec.js, __tests__/server/controllers/users.spec.js, package.json, server/controllers/documentController.js, server/helpers/jwt.js, server/routes/routes.js, server/seeders/20170719104129-users_seeder.js, server/seeders/20180616143254-documents.js, test/mocha.opts, yarn.lock
Fixes #47 
It fixes failing tests on local.
=> Fix failing tests

.gitignore, client/template.html, server/server.js, webpack.config.babel.js
In this PR, the docs page should now work if a user navigates to `/docs`.
=> Fixed docs page
